Cleanup & fix shell-quoting in generated 'env' and 'run-agent.sh' scripts
* Fix shell-quoting of arguments in .gnupg/trezor/`env` and
  .gnupg/trezor/`run-agent.sh` for non-Windows platforms.

* Fix `AttributeError: 'float' object has no attribute 'translate'` when
  passing --cache-expiry-seconds to `*-gpg init` on all platforms.

* Add "exec" to the sh scripts, where appropriate, so that the wrapped
  command replaces the shell, rather than running in a subprocess.

* Move Bourne sh and Windows batch-file templates into separate sections
  of code, since it doesn't make sense to combine them once we're doing
  quoting properly.

* Use standard POSIX /bin/sh syntax in the env script so that this has
  the possibility of working on systems without /bin/bash.